### ISSUE TITLE
Update Readme.MD to include proper paths for running the project

### ISSUE THREAD

**Issue by korir248** [renatosans/ShoppingCartRUST#1]

**Comment by renatosans** [comment]
This project is idle.   The frontend is pending implementation.

**Comment by korir248** [comment]
Will the frontend be written in Rust or some other language/ framework eg React?

**Comment by renatosans** [comment]
Hello there,

The intent was to add a frontend using RUST/WASM with Leptos framework.
Maybe i will implement it using REACT instead.


Em Sáb, 15 de abr de 2023 6:31 AM, Eugene Korir ***@***.***>
escreveu:
